baseURL: "https://inuntac.netlify.com"
languageCode: "it-IT"
title: "inuntac.com"
pygmentsstyle: 'monokai'
googleAnalytics: UA-159935292-1
unsafe: false
# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors

markup:
  goldmark:
    renderer:
      unsafe: true