baseURL: "https://inuntac.netlify.com"
languageCode: "it-IT"
title: "inuntac"
pygmentsstyle: 'monokai'
googleAnalytics: "UA-159935292-1"

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
